### ISSUE TITLE
should depend on logging api and not logging implementation

### ISSUE THREAD

**Issue by nlacombe42** [samuelcampos/usbdrivedetector#10]
Since this is a library you should only depend on a logging API and not its implementation.
This will allow users of the library to choose their logging implementation (for instance I prefer logback).

More specifically, you should depend on org.slf4j:slf4j-api in the maven compile scope (default scope) and NOT org.slf4j:slf4j-simple.
In the test runtime scope you can depend on org.slf4j:slf4j-simple if you want so that you see the logs in your tests.

**Comment by samuelcampos** [comment]
You're absolutely right. Can you check if my latest commit meets your expectations?

**Comment by maatvirtue** [comment]
Looks good :+1: 

This is not urgent for me. Release whenever is the best time for you.
