### ISSUE TITLE
Windows 10 is not supported

### ISSUE THREAD

**Issue by Dgotlieb** [samuelcampos/usbdrivedetector#13]
Hi,

When I'm trying to do it on windows 10 I'm getting:

"no instances available" when trying it from CMD.

Any idea?

**Comment by SnowyCoder** [comment]
It seems that the command changed from win7 "wimc" to win8+ "c:\Windows\System32\wbem\wmic" (because it was removed from the path).
It seems like the constant string that indicates the command is inlined and can't be changed with reflection

**Comment by SnowyCoder** [comment]
Can't write a pull request right now, if anyone wants a quick and dirty fix I wrote one here: https://pastebin.com/0budhvKJ
It should work 90% of the time
