### ISSUE TITLE
Listener Takes time to update status  

### ISSUE THREAD

**Issue by androidlover5842** [samuelcampos/usbdrivedetector#16]
it updates state of device after 5-6 secs delay .

**Comment by fpintaric** [comment]
I'm pretty sure this has to do with the time it takes the OS to actually mount the drive, not the library itself.

**Comment by samuelcampos** [comment]
The library uses a pooling strategy, so you may face a delay. The default interval is 10 seconds. However you can change the polling interval by using:

```java
// Start the device manager using a 5 second pooling interval
USBDeviceDetectorManager driveDetector = new USBDeviceDetectorManager(5000);

// Sett new pooling interval, after device manager initialization.
driveDetector.setPollingInterval(6000);
```

**Comment by androidlover5842** [comment]
thanks
