### ISSUE TITLE
Errors in the workspace after checkout master

### ISSUE THREAD

**Issue by endaobrien** [samuelcampos/usbdrivedetector#30]
I get lots of errors when I check out master (53 to be exact).  

e.g.

log cannot be resolved	AbstractStorageDeviceDetector.java	/usbdrivedetector/src/main/java/net/samuelcampos/usbdrivedetector/detectors	line 83	Java Problem

there are lots of these on log lines.
also other errors.

**Comment by samuelcampos** [comment]
This project is using the project Lombok (https://projectlombok.org/) which writes some of the Java code for you, given some annotations. 
Your IDE needs a plugin to understand those annotations.

**Comment by endaobrien** [comment]
Ah, I see. So Its not a bug. Thanks for the response.
