### ISSUE TITLE
Cannot set polling interval

### ISSUE THREAD

**Issue by leonjones1974** [samuelcampos/usbdrivedetector#32]
```
 if (pollingInterval >= 0) {
            throw new IllegalArgumentException("'pollingInterval' must be greater than 0");
        }
```

**Comment by samuelcampos** [comment]
Where are you seeing the above code?

I can only find another condition which seems to be correct: https://github.com/samuelcampos/usbdrivedetector/blob/master/src/main/java/net/samuelcampos/usbdrivedetector/USBDeviceDetectorManager.java#L77

How are you trying to set the polling interval?

**Comment by leonjones1974** [comment]
Interesting. I’m seeing that in the source that was downloaded along with the artifact. I have several resolvers in my project so I’ll have to look where it actually came from. I’ll check the version at the same time.


Sent from Yahoo Mail for iPhone


On Friday, July 3, 2020, 12:42 pm, Samuel Campos <notifications@github.com> wrote:




Where are you seeing the above code?

I can only find another condition which seems to be correct: https://github.com/samuelcampos/usbdrivedetector/blob/master/src/main/java/net/samuelcampos/usbdrivedetector/USBDeviceDetectorManager.java#L77

How are you trying to set the polling interval?

**Comment by leonjones1974** [comment]
OK. My bad. Version 2.0.0 in maven central has this issue. 2.1.1 is fixed.
Thanks for your help.

**Comment by samuelcampos** [comment]
great news
