### ISSUE TITLE
Regarding external hard disk

### ISSUE THREAD

**Issue by sashi2k** [samuelcampos/usbdrivedetector#36]
Hi

Will this open source provided by you detect an external hard disk?

Thanks,
Sashi

**Comment by sashi2k** [comment]
> Yes, it will

Should it be partitioned as FAT32?

**Comment by samuelcampos** [comment]
The file system shouldn't mater. It should work with FAT32

**Comment by sashi2k** [comment]
> The file system shouldn't mater. It should work with FAT32

It is not detecting. I have an external hard disk with NTFS partition. I created one FAT32 partition. When I plugin the hard disk and run the Java program, it does not show the external hard disk.
