### ISSUE TITLE
Maven central not updated with recent version 2.2

### ISSUE THREAD

**Issue by williamtavares** [samuelcampos/usbdrivedetector#42]
Can you please update the maven repo with the latest version? It looks like the latest version on maven central is 2.1.1

**Comment by samuelcampos** [comment]
Hi William, I was thinking of publishing it to GitHub Packages packages from now on.
However, I'm aware of [this issue which requires authentication even for public repos](https://github.community/t/download-from-github-package-registry-without-authentication/14407). I was hoping it would get fixed sometime soon. However, I think I'm wrong.

Can you afford to use a GitHub authentication token in your project?

**Comment by williamtavares** [comment]
I don't have that setup on my project, if you cant update the maven repo any way you can add the jar on releases under the github project. That way i could just download the jar and insert it in the project.

**Comment by samuelcampos** [comment]
You can download the jar directly from the link on the right side of this page: https://github.com/samuelcampos/usbdrivedetector/packages/1309235

**Comment by williamtavares** [comment]
Thanks, i was able to add it to my project. Unfortunately, looks like the library doesn't detect USB devices on openSUSE Tumbleweed (Latest Version). Is there any way you can check why it doesn't work on this version of Linux?

Thanks for your help

**Comment by cmhulbert** [comment]
If you are still considering updating the Maven version of this artifact, It would be greatly appreciated. I am considering using this in a project I manage, but I would not be able to add an authorization token to the distribution. 

I would love to see [the authorization issue](https://github.community/t/download-from-github-package-registry-without-authentication/14407) resolved, but I think you are right, that it doesn't seem  like a priority for them

**Comment by samuelcampos** [comment]
Hi, I just released the version `2.2.1` to Maven Central. It should be available in a couple hours.

**Comment by samuelcampos** [comment]
Closing this issue, once the new version is now available: https://search.maven.org/artifact/net.samuelcampos/usbdrivedetector/2.2.1/jar
