### ISSUE TITLE
Bug in AbstractStorageDeviceDetector

### ISSUE THREAD

**Issue by 3m5-georg-posselt** [samuelcampos/usbdrivedetector#6]
Hello

in the Function addUSBDevice is a try catch block missing

try {
			USBStorageDevice device = new USBStorageDevice(root);
			listDevices.add(device);
		} catch (IllegalArgumentException e) {
			logger.debug("Could not add Device - IllegalArgumentException: "
					+ e.getMessage());
		}

**Comment by samuelcampos** [comment]
Thank you. I've updated that method with that try catch block.
